name: fismatic
dependencies:
  - python=3
  - jupyter
  - pandas
  - pip
  - pip:
      - autoflake
      - black
      - PyGithub
      - python-docx
      - requests-cache
  - plotly
  - pytest
  - rope
  - scikit-learn
  - spacy
